[package]
name = "animation_helper"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
wfc = { path = "../wfc" }
wfc_image = { path = "../wfc-image" }
coord_2d = "0.3"
pixels = "0.2"
winit = "0.25"
